# Generated by Django 2.1.2 on 2018-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(verbose_name='Requested at')),
                ('uploaded_file', models.CharField(max_length=100)),
                ('processing_time', models.IntegerField()),
                ('action', models.CharField(max_length=200)),
            ],
        ),
    ]
